function createWindow(f)
    global rb1 rb2 rb3 rb4 rb5 rb6 rb7 rb8 f window nr nc box_size square_horizontal square_vertical nrows ncols

  title = uicontrol (f, "style", "text", ...
                    "string", "Select one or more lines, but a pair can't have a blank", ...
                    "Position", [ 10 350 400 50 ]);
                    
    label1 = uicontrol (f, "style", "text", ...
                    "string", "Horizontal Line", ...
                    "Position", [ 10 250 200 50 ]);
    label2 = uicontrol (f, "style", "text", ...
                    "string", "Vertical Line", ...
                    "Position", [ 10 200 200 50 ]);
  ##  label3 = uicontrol (f, "style", "text", ...
  ##                  "string", "Blank", ...
  ##                  "Position", [ 10 150 200 50 ]);
                    
    label4 = uicontrol (f, "style", "text", ...
                    "string", "Pos", ...
                    "Position", [ 220 250 50 50 ]);
    label5 = uicontrol (f, "style", "text", ...
                    "string", "Pos", ...
                    "Position", [ 220 200 50 50 ]);
                    
  ##  label6 = uicontrol (f, "style", "text", ...
  ##                  "string", "Pos", ...
  ##                  "Position", [ 220 150 50 50 ]);
    gp1 = uibuttongroup (f, "Position", [ 0.51, 0.61, 0.45, 0.1]);

    rb1 = uicontrol (gp1, "style", "radiobutton", ...
                    "string", "Top", ...
                    "Position", [ 10 0 50 50 ]);
                    
    rb2 = uicontrol (gp1, "style", "radiobutton", ...
                    "string", "Mid", ...
                    "Position", [ 60 0 50 50 ]);
                    
    rb3 = uicontrol (gp1, "style", "radiobutton", ...
                    "string", "Bottom", ...
                    "Position", [ 110 0 60 50 ]);
                    
    rb7 = uicontrol (gp1, "style", "radiobutton", ...
                    "string", "None", ...
                    "Position", [ 180 0 60 50 ]);
                    
    gp2 = uibuttongroup (f, "Position", [ 0.51, 0.5, 0.45, 0.1]);
               
    rb4 = uicontrol (gp2, "style", "radiobutton", ...
                    "string", "Left", ...
                    "Position", [ 10 0 50 50 ]);
                    
    rb5 = uicontrol (gp2, "style", "radiobutton", ...
                    "string", "Mid", ...
                    "Position", [ 60 0 50 50 ]);
                    
    rb6 = uicontrol (gp2, "style", "radiobutton", ...
                    "string", "Right", ...
                    "Position", [ 110 0 50 50 ]);
                    
    rb8 = uicontrol (gp2, "style", "radiobutton", ...
                    "string", "None", ...
                    "Position", [ 180 0 60 50 ]);

  ##  gp3 = uibuttongroup (f, "Position", [ 0.51, 0.39, 0.4, 0.1]);       
  ##  rb7 = uicontrol (gp3, "style", "radiobutton", ...
  ##                  "string", "1", ...
  ##                  "Position", [ 10 0 50 50 ]);
                    
    btn = uicontrol (f, "style", "pushbutton", ...
                    "string", "Done", ...
                    "Position", [ 430 50 50 50 ], ...
                    "callback", {@buttonPressed});
    
    set(rb1, 'Value', 0)
    set(rb2, 'Value', 0)
    set(rb3, 'Value', 0)
    set(rb4, 'Value', 0)
    set(rb5, 'Value', 0)
    set(rb6, 'Value', 0)
    set(rb7, 'Value', 0)
    
    idx_horz = square_horizontal(nr, nc);
    if idx_horz == 1
      set(rb1, 'Value', 1);
    elseif idx_horz == 2
      set(rb2, 'Value', 1);
    elseif idx_horz == 3
      set(rb3, 'Value', 1);
    else
      set(rb7, 'Value', 1);
    end
    
    idx_vert = square_vertical(nr, nc);
    if idx_vert == 1
      set(rb4, 'Value', 1);
    elseif idx_vert == 2
      set(rb5, 'Value', 1);
    elseif idx_vert == 3
      set(rb6, 'Value', 1);
    else
      set(rb8, 'Value', 1);
    end
endfunction